config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  mount ApplicationAPI => '/api'

  get 'librarian', to: 'librarian#index'
  post 'lending_books', to: 'librarian#lending_books'
  namespace :librarian do
    resources :books
  end

  get    'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  root "books#index"

  resources :authors

  resources :categories

  get 'books', to: 'books#index'

  resources :book_repositories

  resources :users

  devise_for :librarians
  devise_for :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books, through: :book_authors
	has_many :book_authors
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users, through: :user_books
	has_many :user_books
	has_many :authors, through: :book_authors
	has_many :book_authors
	has_many :categories, through: :book_categories
	has_many :book_categories
	accepts_nested_attributes_for :authors
	accepts_nested_attributes_for :categories
end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
	belongs_to :author
	belongs_to :book
end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base
	belongs_to :book
	belongs_to :category
end

app/models/book_repository.rb
class BookRepository < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books, through: :book_categories
	has_many :book_categories
end

app/models/librarian.rb
class Librarian < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
	validates :reg_no, presence: true
	validates :password, presence: true
	validates :password_confirmation, presence: true
	has_secure_password
	has_many :books, through: :user_books
	has_many :user_books
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/controllers/librarian_controller.rb
class LibrarianController < ApplicationController
	before_action :authenticate_librarian!
  def index
  	@user_books = UserBook.all
  	@user_book = UserBook.new
  end

  def lending_books
  	@user = User.find_by(reg_no: params[:user_book][:user][:reg_no])
  	@book = Book.find_by(isbn_no: params[:user_book][:book][:isbn_no])
  	@user_book = UserBook.new(user_id: @user.id, book_id: @book.id, date: Date.today + 10)
  	if @user_book.save
  		redirect_to librarian_path
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(reg_no: params[:session][:reg_no])
    if user && user.authenticate(params[:session][:password])
     	log_in user
      redirect_to books_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
      redirect_to  books_path
    else
      render 'new'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :reg_no, :password, :password_confirmation, :dept, :year)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_repositories_helper.rb
module BookRepositoriesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/librarian_helper.rb
module LibrarianHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/authors/_form.html.slim
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      h2 = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      ul
        - @author.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

= link_to 'Show', @author
'|
= link_to 'Back', authors_path

app/views/authors/index.html.slim
h1 Listing authors

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @authors.each do |author|
      tr
        td = author.name
        td = link_to 'Show', author
        td = link_to 'Edit', edit_author_path(author)
        td = link_to 'Destroy', author, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Author', new_author_path

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.slim
p#notice = notice

p
  strong Name:
  = @author.name

= link_to 'Edit', edit_author_path(@author)
'|
= link_to 'Back', authors_path

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :category_name
    = f.text_field :category_name
  .actions = f.submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th Category name
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.category_name
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Category name:
  = @category.category_name

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path