config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  mount ApplicationAPI => '/api'

  get 'librarian', to: 'librarian#index'
  post 'lending_books', to: 'librarian#lending_books'
  namespace :librarian do
    resources :books
  end

  get    'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  root "books#index"

  resources :authors

  resources :categories

  get 'books', to: 'books#index'

  resources :book_repositories

  resources :users

  devise_for :librarians
  devise_for :admins

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users, through: :user_books
	has_many :user_books
	has_many :authors, through: :book_authors
	has_many :book_authors
	has_many :categories, through: :book_categories
	has_many :book_categories
	accepts_nested_attributes_for :authors
	accepts_nested_attributes_for :categories
end

app/models/librarian.rb
class Librarian < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end
end

app/controllers/librarian/books_controller.rb
class Librarian::BooksController < ApplicationController
  before_action :authenticate_librarian!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @category = Category.find_by(category_name: params[:category][:name])
    respond_to do |format|
      if @book.save
        BookCategory.create(book_id: @book.id, category_id: @category.id)
        @book.authors.create(name: params[:author][:name])
        format.html { redirect_to [:librarian, @book], notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to librarian_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :isbn_no, :quantity)
    end
end

app/controllers/librarian_controller.rb
class LibrarianController < ApplicationController
	before_action :authenticate_librarian!
  def index
  	@user_books = UserBook.all
  	@user_book = UserBook.new
  end

  def lending_books
  	@user = User.find_by(reg_no: params[:user_book][:user][:reg_no])
  	@book = Book.find_by(isbn_no: params[:user_book][:book][:isbn_no])
  	@user_book = UserBook.new(user_id: @user.id, book_id: @book.id, date: Date.today + 10)
  	if @user_book.save
  		redirect_to librarian_path
  	end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/librarian_helper.rb
module LibrarianHelper
end

app/views/librarian/books/_form.html.slim
.row
  .col-md-6
    = form_for [:librarian, @book] do |f|
      - if @book.errors.any?
        #error_explanation
          h2 = "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
          ul
            - @book.errors.full_messages.each do |message|
              li = message

      .field.form-group
        .row
          .col-md-2
            = f.label :name
          .col-md-4
            = f.text_field :name, class: "form-control"
      .field.form-group
        .row
          .col-md-2
            = f.label :isbn_no
          .col-md-4
            = f.text_field :isbn_no, class: "form-control"
      .field
        .row.form-group
          .col-md-2
            = f.label :quantity
          .col-md-4
            = f.number_field :quantity, class: "form-control" 
      .field
        = fields_for :category, @book.categories do |category|
          .row.form-group
            .col-md-2
              = category.label :category_name
            .col-md-4
              = category.select(:name, Category.all.map {|category| [category.category_name]}, class: "form-control", id: "librarian_category")
              / = select_tag "",  options_for_select(Category.all.map {|category| [category.category_name]}), id: "librarian_category" 
      .field
        = fields_for :author, @book.authors do |author|
          .row.form-group
            .col-md-2
              = author.label :author_name
            .col-md-4
              = author.text_field :name, class: "form-control" 
      
      .actions = f.submit 'Add book', class: 'btn btn-default'

app/views/librarian/books/edit.html.slim
h1 Editing book

== render 'form'

= link_to 'Show', [:librarian, @book]
'|
= link_to 'Back', librarian_books_path

app/views/librarian/books/index.html.slim
.panel.panel-default
  .panel-heading
    | Listing Books
  table.table
    thead
      tr
        th Name
        th Isbn no
        th Quantity
        th Category
        th Author
        th
        th
        th

    tbody
      - @books.each do |book|
        tr
          td = book.name
          td = book.isbn_no
          td = book.quantity
          td = book.categories.first.category_name
          td = book.authors.first.name
          td = link_to 'Show', [:librarian, book]
          td = link_to 'Edit', edit_librarian_book_path(book)
          td = link_to 'Destroy',[:librarian, book], data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Book', new_librarian_book_path

app/views/librarian/books/new.html.slim
h1 New book

== render 'form'

= link_to 'Back', librarian_books_path

app/views/librarian/books/show.html.slim
p#notice = notice

p
  strong Name:
  = @book.name
p
  strong Isbn no:
  = @book.isbn_no
p
  strong Quantity:
  = @book.quantity

= link_to 'Edit', edit_librarian_book_path(@book)
'|
= link_to 'Back', librarian_books_path